name: CI_RELEASE_BODYBUILDER

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
